services:
 db:
   image: postgres:17
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env
 
 web:
   build: .
   container_name: django-pizzeria
   command: gunicorn circular_pi_pizza.wsgi:application --workers 3 --bind 0.0.0.0:8000
   volumes:
     - static_volume:/app/staticfiles
   expose:
     - 8000
   depends_on:
     - db
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${DATABASE_USERNAME}
     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
     DATABASE_HOST: ${DATABASE_HOST}
     DATABASE_PORT: ${DATABASE_PORT}
   env_file:
     - .env

 nginx:
   build: ./nginx
   volumes:
     - static_volume:/app/staticfiles
   ports:
     - 8000:80
   depends_on:
     - web

volumes:
   postgres_data:
   static_volume:
