# Generated by Django 4.2.2 on 2023-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='prize',
            field=models.FloatField(default=0.0, max_length=5),
        ),
    ]
