# Generated by Django 4.2.2 on 2023-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pizza_ingredients_alter_pizza_name_alter_pizza_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='prize',
            new_name='priceLarge',
        ),
        migrations.AddField(
            model_name='pizza',
            name='priceMedium',
            field=models.FloatField(default=0.0, max_length=5),
        ),
    ]
