# Generated by Django 4.2.2 on 2023-08-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_prize_pizza_pricelarge_pizza_pricemedium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='priceLarge',
            new_name='price_large',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='priceMedium',
            new_name='price_medium',
        ),
    ]
