# Generated by Django 4.2.2 on 2023-10-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('ingredients', models.CharField(default='', max_length=250)),
                ('price_medium', models.FloatField(default=0.0, max_length=5)),
                ('price_large', models.FloatField(default=0.0, max_length=5)),
                ('type', models.CharField(default='', max_length=50)),
                ('hot', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
            ],
        ),
    ]
