# Generated by Django 4.2.2 on 2023-10-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_alter_pizza_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='vegetarian',
        ),
    ]
