# Generated by Django 4.2.2 on 2023-10-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_remove_pizza_hot_remove_pizza_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
