# Generated by Django 4.2.2 on 2023-10-22 21:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0010_order_alter_pizza_ingredients_alter_pizza_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL'),
        ),
    ]
