# Generated by Django 4.2.2 on 2023-10-29 18:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzeria', '0015_alter_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in progress', 'In progress'), ('in delivery', 'In delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='in progress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredients',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price_large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price_medium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('medium', 'Medium'), ('large', 'Large')], default='medium')),
                ('crust', models.CharField(choices=[('thin', 'Thin'), ('thick', 'Thick')], default='thin')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.pizza')),
            ],
        ),
    ]
