# Generated by Django 4.2.2 on 2023-10-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0016_order_status_order_user_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
